export const goldenExperienceProfile = {
  runtimeSeconds: {
    min: 90,
    target: 105,
    max: 120,
  },
  narration: {
    minWords: 220,
    targetWords: 260,
    maxWords: 300,
    tone: "engineering-explainer",
    avoid: [
      "reading documentation verbatim",
      "bullet-list narration",
      "section-by-section summary",
      "this section explains",
    ],
  },
  scenes: {
    min: 7,
    target: 8,
    max: 9,
    averageDurationSeconds: 12,
  },
  visuals: {
    style: ["Apple", "Stripe", "Linear", "Vercel"],
    textDensity: "low",
    motionDensity: "high",
    diagramDensity: "high",
    useVisualMetaphors: true,
    preferSvg: true,
    preferAnimatedDiagrams: true,
    avoidSlideLayouts: true,
  },
  animation: {
    requireContinuousMotion: true,
    requireSvgPathAnimations: true,
    requireCameraMovement: true,
    requireProgressiveReveal: true,
    requireMorphingLayouts: true,
    avoidStaticFramesLongerThanSeconds: 2,
  },
  storyArc: [
    "hook",
    "problem",
    "pain",
    "solution",
    "guided walkthrough",
    "benefits",
    "developer experience",
    "conclusion",
  ],
  visualPrimitives: [
    "AnimatedWorkflow",
    "PipelineFlow",
    "TraceabilityChain",
    "ApprovalGate",
    "ArtifactRegistry",
    "ParallelLanes",
    "ValidationGate",
    "TerminalSequence",
    "DiagramReveal",
    "BenefitCards",
    "FloatingDocumentCloud",
    "ConnectedNodeGraph",
    "CameraRail",
    "PathDraw",
    "ProgressiveHighlight",
    "MorphingCardStack",
    "SceneTransition",
  ],
} as const;

export type GoldenExperienceProfile = typeof goldenExperienceProfile;
export type VisualPrimitiveName = (typeof goldenExperienceProfile.visualPrimitives)[number];
